1) ListaDoblementeEnlazada#Lista Se extrae el primer elemento de la Lista      Failure/Error: expect(@list.extract_head.value).to eq(1)
     NoMethodError:
       undefined method `extract_head' for #<ListaDoblementeEnlazada:0x000000017e59b8>
     # ./spec/alimento_spec.rb:41:in `block (3 levels) in <top (required)>'