1) ListaDoblementeEnlazada#Lista Se puede insertar un elemento en la Lista      Failure/Error: expect(@list.insert(1)).to eq(true)
     NoMethodError:
       undefined method `insert' for #<ListaDoblementeEnlazada:0x00000002218368 @tail=nil, @head=nil>
     # ./spec/alimento_spec.rb:30:in `block (3 levels) in <top (required)>'