1) ListaDoblementeEnlazada#Lista Se extrae el ultimo elemento de la Lista      Failure/Error: expect(@lista.extraer_final).to eq(7)
     NoMethodError:
       undefined method `extraer_final' for nil:NilClass
     # ./spec/alimento_spec.rb:44:in `block (3 levels) in <top (required)>'