1) Aibc#AIBC Probando aibc      Failure/Error: expect(@yogurt.aibc).to eq([1,3,3])
     NoMethodError:
       undefined method `aibc' for #<Aibc:0x0000000263bcb0>
     # ./spec/alimento_spec.rb:15:in `block (3 levels) in <top (required)>'