1) ListaDoblementeEnlazada #Debe existir una Lista con su cabeza error      Failure/Error: expect(@list.head).to eq(nil)
     NoMethodError:
       undefined method `head' for #<ListaDoblementeEnlazada:0x00000002ade1a0>
     # ./spec/alimento_spec.rb:23:in `block (2 levels) in <top (required)>'